# Datos {menu-title="Datos utilizados"}

::: {.subtitle}

Fuentes de datos utilizadas en el análisis

:::

::: {.metodo-intro style="margin: -14px auto 0 auto;"}

La metodología integra información de **transporte público, población flotante, oportunidades urbanas y red peatonal**.

:::

:::: {.columns-datos}

::: {.column-datos-info}

::: {.dato-tipo}

🚌 **Oferta de transporte público**

:::

**7 días** de observaciones<br>
**1.481 buses** monitoreados<br>
**11–17 mayo 2026**<br>
**05:00–24:00 h**<br>
**Eventos GPS / GTFS-RT**

::: {.fuente-box}

**Fuente:** GTFS-RT

:::

:::


::: {.column-datos-info}

::: {.dato-tipo}

📶 **Población flotante**

:::

**Unidad espacial:** H3 resolución 9  
**Resolución temporal:** 1 hora  
**Horario:** 07:00–22:00 h  
**Período:** semana tipo de agosto de 2025

::: {.fuente-box}

**Fuente:** Crowds – Entel Digital

:::

:::


::: {.column-datos-info}

::: {.dato-tipo}

📍 **Oportunidades urbanas**

:::

**POI:** localización y categoría  
**Disponibilidad:** horarios de apertura  
**Atractividad:** rating y número de reseñas  

::: {.fuente-box}

**Fuente:** Google Places

:::

:::


::: {.column-datos-info}

::: {.dato-tipo}

🚶 **Red peatonal**

:::

**Fuente espacial:** OpenStreetMap  
**Uso:** cálculo de rutas y tiempos de caminata  
**Aplicación:** impedancia entre H3/POI y acceso

::: {.fuente-box}

**Fuente:** OpenStreetMap

:::

:::

::::
