# Datos {menu-title="Áreas de análisis"}

::: {.subtitle}

Áreas seleccionadas mediante PTAL

:::

```{=html}
<iframe
  id="areas-poi"
  class="map-pois"
  src="../../Html/poi_viewer/map_poi.html"
  loading="eager"
  style="border: none;">
</iframe>

<script>
let areasEnviadas = false;

function enviarAreas() {
  if (areasEnviadas) return;

  const iframeAreasPois = document.getElementById("areas-poi");

  if (!iframeAreasPois || !iframeAreasPois.contentWindow) return;

  const dataEnviar = {
    area_1: {
      area_name: "Área Baja",

      area_seleccionada:
        "../../Data/Area Baja/area_seleccionada.json",

      accesos: {
        "Acceso 1": [
          "../../Data/Area Baja/Data Access/e5eabf16-47d9-4885-9998-43b372f4a949.json",
          "../../Data/Area Baja/Data Access Poi Distance/01M1A5F5VYVE.json"
        ],

        "Acceso 2": [
          "../../Data/Area Baja/Data Access/acces-baja-2.json",
          "../../Data/Area Baja/Data Access Poi Distance/01M1A6FZMJSQ.json"
        ]
      },

      data_places:
        "../../Data/Area Baja/Data Places/01M1A6FZMJSQ.json"
    },

    area_2: {
      area_name: "Área Intermedia",

      area_seleccionada:
        "../../Data/Area Intermedia/area_seleccionada.json",

      accesos: {
        "Acceso 1": [
          "../../Data/Area Intermedia/Data Access/83f9742c-bb41-48c4-9719-8f9f4524f8ea.json",
          "../../Data/Area Intermedia/Data Access Poi Distance/01KVKQ099Z48.json"
        ],

        "Acceso 2": [
          "../../Data/Area Intermedia/Data Access/7052a9fc-afd2-4537-967a-d0ce42f8801e.json",
          "../../Data/Area Intermedia/Data Access Poi Distance/01M0ZVTH74AW.json"
        ]
      },

      data_places:
        "../../Data/Area Intermedia/Data Places/01KVKQ099Z48.json"
    },

    area_3: {
      area_name: "Área Alta",

      area_seleccionada:
        "../../Data/Area Alta/area_seleccionada.json",

      accesos: {
        "Acceso 1": [
          "../../Data/Area Alta/Data Access/056fd607-aa8d-497d-96b1-1fe8fc61880f.json",
          "../../Data/Area Alta/Data Access Poi Distance/01KTYZJYNBDM.json"
        ],

        "Acceso 2": [
          "../../Data/Area Alta/Data Access/09418028-7292-44cb-9a1a-cc80d3b66ff1.json",
          "../../Data/Area Alta/Data Access Poi Distance/01KV7NVA96FY.json"
        ]
      },

      data_places:
        "../../Data/Area Alta/Data Places/01KTYZJYNBDM.json"
    }
  };

  iframeAreasPois.contentWindow.postMessage(
    {
      type: "cargar_areas_poi",
      data_enviar: dataEnviar
    },
    "*"
  );

  areasEnviadas = true;
}

const iframeAreasPois = document.getElementById("areas-poi");

iframeAreasPois.addEventListener("load", () => {
  setTimeout(enviarAreas, 40);
});
</script>