# Metodología {menu-title="Caracterización de oportunidades"}

::: {.subtitle}

Caracterización de las oportunidades urbanas

:::

::: {.componentes-intro}

Cada POI se caracteriza según su **disponibilidad temporal** 
$\big(B^{\mathrm{POI}}_{i,h}\big)$, **atractividad observada** 
$\big(G_i^{\mathrm{Review}}\big)$ e **importancia funcional–temporal** 
$\big(W^{\mathrm{POI}}_{i,h}\big)$.

:::


::: {.poi-components}


::: {.poi-component}

::: {.poi-component-title}

**Disponibilidad temporal**

:::

::: {.poi-formula}

$$
B^{\text{POI}}_{i,h}
=
\begin{cases}
1,   & \text{abierto} \\[3pt]
0.5, & \text{sin información} \\[3pt]
0,   & \text{cerrado}
\end{cases}
$$

:::

::: {.poi-component-desc}

Los **horarios de apertura condicionan la disponibilidad temporal** de las oportunidades urbanas [@NEUTENS2012128; @mckenzie2015how].

:::

:::


::: {.poi-component}

::: {.poi-component-title}

**Atractividad observada**

:::

::: {.poi-formula}

$$
G_{i}^{\text{Review}}
=
\min\left\{
1,\,
\frac{\text{Rating}_{i}}{5}
\cdot
\frac{
\ln\!\left(1+\text{N_rating}_{i,c}\right)
}{
\ln\!\left(
1+P_{90}\!\left(\text{N_rating}_{c}\right)
\right)
}
\right\}
$$

:::

::: {.poi-component-desc}

Las oportunidades pueden diferenciarse según su **atractividad y características asociadas al destino** [@psyllidis2022points; @moyagomez2018dynamic].

:::

:::


::: {.poi-component}

::: {.poi-component-title}

**Importancia funcional–temporal**

:::

::: {.poi-formula}

$$
W^{\text{POI}}_{i,h}
=
\sqrt{
\frac{
w^{\text{class}}_{g(i)}
\cdot
w^{\text{cat}}_{c(i)}
\cdot
w^{\text{time}}_{c(i),h}
}{25}
}
$$

:::

::: {.poi-component-desc}

La **función del POI y sus patrones temporales** permiten distinguir la relevancia de las oportunidades a lo largo del día [@psyllidis2022points; @betancourt2023temporal].

:::

:::


:::